FROM node:20-slim

WORKDIR /app

COPY SIH_PROJECT/package.json /app/package.json
RUN npm install

COPY SIH_PROJECT /app

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]